#!/bin/sh

set -e

MODULE_DIR="/usr/lib/"
MODULES="libXnDeviceSensorV2.so libXnDeviceFile.so"

if [ "$1" = "configure" ]; then
	for module in $MODULES; do
		niReg -r $MODULE_DIR/$module /etc/primesense
	done
fi

#DEBHELPER#
